### PR TITLE
[sc-101330] Add base URL to next record URL pagination

### PR DESCRIPTION
**Pull request by alexbourret**

### CODE REVIEW

**Comment by liamlynch-data** [comment]
@alexbourret Hi - I have done some testing on this and noticed a small thing - on the dataset, if you check the box for relative URL but then forget to put a URL in, it appears to work on the test then fails later on populating it. Perhaps we can catch the error earlier or make sure they don't forget to fill in the value?

image

**Review by liamlynch-data — APPROVED** [review]
The code looks good to me. Perhaps it is possible to do something about the small issue I noticed (comment above), but probably not crucial.

**Comment by alexbourret** [comment]
👍 I added an assertion + meaningful error message in [9ec6f73](https://github.com/dataiku/dss-plugin-api-connect/pull/28/commits/9ec6f730b0a85bc8facad6db2ec3686247353838)

**Comment by liamlynch-data** [comment]
@alexbourret great - had a quick test, all looks good to me!

**Pull request merged**
